cache:
  paths:
  - node_modules/

stages:
  - test
  - build
  - prod

unit_test:
  image: node:6-alpine
  stage: test
  variables:
    NODE_ENV: test
  before_script:
    # Install yarn
    - yarn
  script:
    - yarn test
  only:
    - dev
    - master

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
    CI_REGISTRY: registry.gitlab.com
    CONTAINER_IMAGE: registry.gitlab.com/theykk/$CI_PROJECT_NAME #Workaround https://gitlab.com/gitlab-org/gitlab-ce/issues/23339

  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    
    - docker build --pull -t $CONTAINER_IMAGE:$CI_COMMIT_SHA .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
  only:
    - dev
    - master
prod:
  image: docker:latest
  stage: prod
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
    CI_REGISTRY: registry.gitlab.com
    CONTAINER_IMAGE: registry.gitlab.com/theykk/$CI_PROJECT_NAME #Workaround https://gitlab.com/gitlab-org/gitlab-ce/issues/23339

  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    
    - docker build --pull -t $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:latest
  only:
    - master