cache:
  paths:
  - node_modules/


image: docker:latest

stages:
  - test
  - build
  - prod
  - stable

before_script:
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

variables:
  CONTAINER_IMAGE_NAME: 'theykk/$CI_PROJECT_NAME'
  CONTAINER_GENERAL_IMAGE: '${CONTAINER_IMAGE_NAME}:${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}'
  CONTAINER_TAGGED_IMAGE: '${CONTAINER_IMAGE_NAME}:${CI_COMMIT_REF_NAME}_${CI_COMMIT_TAG}'
  CONTAINER_LATEST_IMAGE:  '${CONTAINER_IMAGE_NAME}:latest'
  

services:
    - docker:dind

variables:
    DOCKER_DRIVER: overlay

unit_test:
  image: node:6-alpine
  stage: test
  variables:
    NODE_ENV: test
  before_script:
    # Install yarn
    - yarn
  script:
    - yarn test

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_GENERAL_IMAGE .
    - docker push $CONTAINER_GENERAL_IMAGE
  only:
    - branches
  except:
    - master

prod:
  stage: prod
  script:
    - docker build --pull -t $CONTAINER_LATEST_IMAGE .
    - docker push $CONTAINER_LATEST_IMAGE
  only:
    - master

stable:
  stage: stable
  script:
    - docker build --pull -t $CONTAINER_TAGGED_IMAGE .
    - docker push $CONTAINER_TAGGED_IMAGE
  only:
    - tags
