cache:
  paths:
  - node_modules/

stages:
  - test
  - build

unit_test:
  image: node:6-alpine
  stage: test
  variables:
    NODE_ENV: test
  before_script:
    # Install yarn
    - yarn
  script:
    - yarn test
    - yarn run prettier --list-different

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
    CI_REGISTRY: registry.gitlab.com
    CI_REGISTRY_IMAGE: registry.gitlab.com/PROJECT_NAME
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:latest" .
    - docker push "${CI_REGISTRY_IMAGE}:latest"
  only:
    - master